version: '3'
services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/moemoe89/practicing-solr-golang
    container_name: practice_solr_app
    restart: always
    ports:
      - "8785:8785"
    tty: true
    depends_on:
      - solr
    networks:
      - fullstack
  solr:
    container_name: practice_solr
    image: solr:8
    ports:
     - "8983:8983"
    command:
      - solr-precreate
      - collection1
    networks:
      - fullstack
volumes:
  data:
networks:
  fullstack:
    driver: bridge